labels: [os, arch]
fetchers:
  dockerhub_pulls:
    - name: anon_dev_dockerhub
      owner: svforte
      repo: anon-dev
    - name: anon_stage_dockerhub
      owner: svforte
      repo: anon-stage
    - name: anon_live_dockerhub
      owner: svforte
      repo: anon
  github_releases:
    - name: anon_dev_github_releases
      owner: ATOR-Development
      repo: ator-protocol
      assets_regexp: ^anon.+-dev-.+\.deb
      labels:
        os: 'anon.+(bookworm|bullseye|buster|jammy|focal).+\.deb'
        arch: '(amd64|arm64)\.deb'
    - name: anon_stage_github_releases
      owner: ATOR-Development
      repo: ator-protocol
      assets_regexp: ^anon.+-stage-.+\.deb
      labels:
        os: 'anon.+(bookworm|bullseye|buster|jammy|focal).+\.deb'
        arch: '(amd64|arm64)\.deb'
    - name: anon_live_github_releases
      owner: ATOR-Development
      repo: ator-protocol
      assets_regexp: ^anon.+-live-.+\.deb
      labels:
        os: 'anon.+(bookworm|bullseye|buster|jammy|focal).+\.deb'
        arch: '(amd64|arm64)\.deb'
  nginx_access_log:
    - name: anon_dev_debian_repo
      access_log_path: "/alloc/data/access.log"
      access_log_regexp: '"GET /pool/.+anon_[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-dev.+\.deb HTTP\/1\.1" 200'
      labels:
        os: 'anon.+(bookworm|bullseye|buster|jammy|focal).+\.deb'
        arch: '(amd64|arm64)\.deb'
    - name: anon_stage_debian_repo
      access_log_path: "/alloc/data/access.log"
      access_log_regexp: '"GET /pool/.+anon_[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-stage.+\.deb HTTP\/1\.1" 200'
      labels:
        os: 'anon.+(bookworm|bullseye|buster|jammy|focal).+\.deb'
        arch: '(amd64|arm64)\.deb'
    - name: anon_live_debian_repo
      access_log_path: "/alloc/data/access.log"
      access_log_regexp: '"GET /pool/.+anon_[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-live.+\.deb HTTP\/1\.1" 200'
      labels:
        os: 'anon.+(bookworm|bullseye|buster|jammy|focal).+\.deb'
        arch: '(amd64|arm64)\.deb'
